# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-31 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171231_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='website',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=140),
            preserve_default=False,
        ),
    ]
