# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180109_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_images',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
