# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-12 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180112_2028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_images',
            new_name='profile_image',
        ),
    ]
